---
title: "Glycosyltransferases and glycosidases in Treg activation"
output:
  html_notebook:
    css: tabbed_notebook.css
---


```{r setup, include=FALSE}
library(knitr)
library(ggplot2)
options(width = 100)

opts_chunk$set(
  warning=FALSE,
  message=FALSE,
  include=FALSE
)
```

Collaborators: [Paul Crocker](), [Gavuthami Murugesan](), [Gang Wu]()

[Proposal]()

# 14/05/2019

Downloaded FASTQ file from Basespace using basemount (direct download does not work in Linux). Using a modified Snakemake file copied from another project (trypseq). Starting routine analysis. Created conda environment with (hopefully) all necessary packages. Running snakamake. 

Oh joy of joys. I've recently upgraded to R 3.6, which means that now I need to re-install all the libraries. This takes time...

# 15/05/2019

Bedgraph intersect failed due to lack of memory. The trick is to sort bed and bed window files and then use `-sorted` option, which is much more memory efficient (and faster!).

Working on the report and Shiny app. Took some time to get the app running, as the new selection (all/glyco) messed up everything.

# 16/05/2019

Improving shiny app. Setting up access.

Problems loading RData on the shiny server. I turns out R 3.3 on the server could not read .RData file from the most recent R 3.6 on my box. Fortunately, I could save it as an older version. Note to self: workspace format version 2 is for R 1.4-3.5, version 3 is from 3.5.0.




